def build_platforms(username):
    return {
        # Social media platforms
        "Facebook": (f"https://www.facebook.com/{username}", False),
        "Instagram": (f"https://www.instagram.com/{username}/", False),
        "Twitter": (f"https://twitter.com/{username}", False),
        "LinkedIn": (f"https://www.linkedin.com/in/{username}/", False),
        "YouTube": (f"https://www.youtube.com/@{username}", False),
        "TikTok": (f"https://www.tiktok.com/@{username}", False),
        "Snapchat": (f"https://www.snapchat.com/add/{username}", False),
        "Pinterest": (f"https://www.pinterest.com/{username}/", False),
        "Reddit": (f"https://www.reddit.com/user/{username}/", False),
        "Tumblr": (f"https://{username}.tumblr.com/", True),
        "Medium": (f"https://medium.com/@{username}", False),
        "WordPress": (f"https://{username}.wordpress.com/", True),
        "Substack": (f"https://{username}.substack.com/", True),
        "Mastodon": (f"https://mastodon.social/@{username}", False),
        "Bluesky": (f"https://bsky.app/profile/{username}.bsky.social", False),
        "Koo": (f"https://www.kooapp.com/profile/{username}", False),
        "MeWe": (f"https://mewe.com/i/{username}", False),
        "Parler": (f"https://parler.com/{username}", False),

        # Messaging platforms
        "Telegram": (f"https://t.me/{username}", False),
        "Discord": (f"https://discord.com/users/{username}", False),
        "Signal": (f"https://signal.me/#p/{username}", False),
        "WhatsApp": (f"https://wa.me/{username}", False),
        "Messenger": (f"https://www.facebook.com/{username}", False),

        # Developer platforms
        "GitHub": (f"https://github.com/{username}", False),
        "GitLab": (f"https://gitlab.com/{username}", False),
        "Bitbucket": (f"https://bitbucket.org/{username}", False),
        "StackOverflow": (f"https://stackoverflow.com/users/{username}", False),
        "CodePen": (f"https://codepen.io/{username}", False),
        "JSFiddle": (f"https://jsfiddle.net/user/{username}/", False),

        # Creative and design
        "Dribbble": (f"https://dribbble.com/{username}", False),
        "Behance": (f"https://www.behance.net/{username}", False),
        "Flickr": (f"https://www.flickr.com/people/{username}/", False),
        "DeviantArt": (f"https://www.deviantart.com/{username}", False),
        "ArtStation": (f"https://www.artstation.com/{username}", False),
        "500px": (f"https://500px.com/p/{username}", False),

        # Video and streaming
        "Twitch": (f"https://www.twitch.tv/{username}", False),
        "Vimeo": (f"https://vimeo.com/{username}", False),
        "Dailymotion": (f"https://www.dailymotion.com/{username}", False),
        "Bilibili": (f"https://space.bilibili.com/{username}", False),

        # Gaming
        "Steam": (f"https://steamcommunity.com/id/{username}", False),
        "Roblox": (f"https://www.roblox.com/users/{username}/profile", False),
        "Epic Games": (f"https://www.epicgames.com/id/{username}", False),
        "Xbox": (f"https://account.xbox.com/en-us/Profile?gamertag={username}", False),
        "PlayStation": (f"https://my.playstation.com/{username}", False),
        "Twitch": (f"https://www.twitch.tv/{username}", False),
        "Chess.com": (f"https://www.chess.com/member/{username}", False),
        "Lichess": (f"https://lichess.org/@/{username}", False),

        # Adult / NSFW (be cautious with public use)
        "Pornhub": (f"https://www.pornhub.com/users/{username}", False),
        "Redtube": (f"https://www.redtube.com/users/{username}", False),
        "XVideos": (f"https://www.xvideos.com/profiles/{username}", False),
        "XHamster": (f"https://xhamster.com/users/{username}", False),

        # E-commerce & marketplaces
        "eBay": (f"https://www.ebay.com/usr/{username}", False),
        "Etsy": (f"https://www.etsy.com/shop/{username}", False),
        "Depop": (f"https://www.depop.com/{username}/", False),
        "AliExpress": (f"https://www.aliexpress.com/store/{username}", False),
        "Amazon": (f"https://www.amazon.com/shop/{username}", False),

        # Crypto & finance
        "CoinMarketCap": (f"https://coinmarketcap.com/currencies/{username}/", False),
        "Coinbase": (f"https://www.coinbase.com/{username}", False),
        "Binance": (f"https://www.binance.com/en/user/{username}", False),
        "Robinhood": (f"https://robinhood.com/{username}", False),
        "TradingView": (f"https://www.tradingview.com/u/{username}/", False),

        # Forums
        "Quora": (f"https://www.quora.com/profile/{username}", False),
        "4chan": (f"https://boards.4chan.org/user/{username}", False),
        "HackerNews": (f"https://news.ycombinator.com/user?id={username}", False),
        "Lemmy": (f"https://lemmy.world/u/{username}", False),

        # Blogging / CMS
        "Ghost": (f"https://{username}.ghost.io", True),
        "Blogger": (f"https://{username}.blogspot.com", True),
        "Notion": (f"https://{username}.notion.site", True),

        # Fitness / lifestyle
        "Strava": (f"https://www.strava.com/athletes/{username}", False),
        "Fitbit": (f"https://www.fitbit.com/user/{username}", False),

        # Education & learning
        "Khan Academy": (f"https://www.khanacademy.org/profile/{username}", False),
        "Coursera": (f"https://www.coursera.org/user/{username}", False),
        "Udemy": (f"https://www.udemy.com/user/{username}", False),

        # Others
        "Clubhouse": (f"https://www.clubhouse.com/@{username}", False),
        "Letterboxd": (f"https://letterboxd.com/{username}/", False),
        "Last.fm": (f"https://www.last.fm/user/{username}", False),
        "Goodreads": (f"https://www.goodreads.com/user/show/{username}", False),
        "IMDb": (f"https://www.imdb.com/user/{username}/", False),
        "SoundCloud": (f"https://soundcloud.com/{username}", False),
        "Mixcloud": (f"https://www.mixcloud.com/{username}/", False),
        "Anchor": (f"https://anchor.fm/{username}", False),
        "ReverbNation": (f"https://www.reverbnation.com/{username}", False),
        "Bandcamp": (f"https://{username}.bandcamp.com", True),
    "Dev.to": (f"https://dev.to/{username}", False),
        "Trello": (f"https://trello.com/{username}", False),
        "Canva": (f"https://www.canva.com/{username}", False),
        "Figma": (f"https://www.figma.com/@{username}", False),
        "ProductHunt": (f"https://www.producthunt.com/@{username}", False),
        "AngelList": (f"https://angel.co/u/{username}", False),
        "Crunchbase": (f"https://www.crunchbase.com/person/{username}", False),
        "IndieHackers": (f"https://www.indiehackers.com/{username}", False),
        "Hashnode": (f"https://hashnode.com/@{username}", False),
        "Gumroad": (f"https://{username}.gumroad.com", True),
        "Payhip": (f"https://payhip.com/{username}", False),
        "Ko-fi": (f"https://ko-fi.com/{username}", False),
        "BuyMeACoffee": (f"https://www.buymeacoffee.com/{username}", False),
        "Patreon": (f"https://www.patreon.com/{username}", False),
        "TeeSpring": (f"https://teespring.com/stores/{username}", False),
        "Spreadshirt": (f"https://shop.spreadshirt.com/{username}", False),
        "Zazzle": (f"https://www.zazzle.com/{username}", False),
        "CafePress": (f"https://www.cafepress.com/profile/{username}", False),
        "Skillshare": (f"https://www.skillshare.com/user/{username}", False),
        "EdX": (f"https://www.edx.org/user/{username}", False),
        "FutureLearn": (f"https://www.futurelearn.com/profiles/{username}", False),
        "Kaggle": (f"https://www.kaggle.com/{username}", False),
        "Hackerrank": (f"https://www.hackerrank.com/{username}", False),
        "Codeforces": (f"https://codeforces.com/profile/{username}", False),
        "TopCoder": (f"https://www.topcoder.com/members/{username}", False),
        "Replit": (f"https://replit.com/@{username}", False),
        "TryHackMe": (f"https://tryhackme.com/p/{username}", False),
        "HackTheBox": (f"https://app.hackthebox.com/profile/{username}", False),
        "ExploitDB": (f"https://www.exploit-db.com/author/{username}", False),
        "SecurityTrails": (f"https://securitytrails.com/blog/{username}", False),
        "PacketStorm": (f"https://packetstormsecurity.com/files/by-name/{username}.html", False),
        "Glitch": (f"https://glitch.com/@{username}", False),
        "Vercel": (f"https://vercel.com/{username}", False),
        "Netlify": (f"https://app.netlify.com/teams/{username}/overview", False),
        "Surge": (f"https://{username}.surge.sh", True),
        "Render": (f"https://dashboard.render.com/{username}", False),
        "Fly.io": (f"https://fly.io/dashboard/apps/{username}", False),
        "Cloudflare Pages": (f"https://pages.cloudflare.com/{username}", False),
        "Firebase": (f"https://{username}.web.app", True),
        "Vivaldi Forum": (f"https://forum.vivaldi.net/user/{username}", False),
        "Mozilla Support": (f"https://support.mozilla.org/en-US/user/{username}", False),
        "Opera Forums": (f"https://forums.opera.com/user/{username}", False),
        "Debian Forums": (f"https://forums.debian.net/memberlist.php?mode=viewprofile&u={username}", False),
        "Ubuntu Forums": (f"https://ubuntuforums.org/member.php?username={username}", False),
        "Arch Forums": (f"https://bbs.archlinux.org/profile.php?id={username}", False),
        "LibreOffice": (f"https://ask.libreoffice.org/u/{username}", False),
        "OpenAI Community": (f"https://community.openai.com/u/{username}", False),
        "Adobe": (f"https://community.adobe.com/t5/user/viewprofilepage/user-id/{username}", False),
        "Autodesk": (f"https://forums.autodesk.com/t5/user/viewprofilepage/user-id/{username}", False),
        "Unity": (f"https://forum.unity.com/members/{username}", False),
        "Unreal Engine": (f"https://forums.unrealengine.com/u/{username}", False),
        "GDevelop": (f"https://forum.gdevelop.io/u/{username}", False),
        "Godot": (f"https://forum.godotengine.org/user/{username}", False),
        "Itch.io": (f"https://{username}.itch.io", True),
        "GameJolt": (f"https://gamejolt.com/@{username}", False),
        "ModDB": (f"https://www.moddb.com/members/{username}", False),
        "IndieDB": (f"https://www.indiedb.com/members/{username}", False),
        "Gamebanana": (f"https://gamebanana.com/members/{username}", False),
        "FanFiction": (f"https://www.fanfiction.net/u/{username}/", False),
        "AO3": (f"https://archiveofourown.org/users/{username}/", False),
        "Wattpad": (f"https://www.wattpad.com/user/{username}", False),
        "Quotev": (f"https://www.quotev.com/{username}", False),
        "RoyalRoad": (f"https://www.royalroad.com/profile/{username}", False),
        "Tapas": (f"https://tapas.io/{username}", False),
        "Webtoons": (f"https://www.webtoons.com/en/creator/{username}", False),
        "MyAnimeList": (f"https://myanimelist.net/profile/{username}", False),
        "AniList": (f"https://anilist.co/user/{username}/", False),
        "Kitsu": (f"https://kitsu.io/users/{username}", False),
        "Letterboxd": (f"https://letterboxd.com/{username}/", False),
        "Trakt": (f"https://trakt.tv/users/{username}", False),
        "TV Time": (f"https://www.tvtime.com/en/user/{username}", False),
        "Discogs": (f"https://www.discogs.com/user/{username}", False),
        "Bandlab": (f"https://www.bandlab.com/{username}", False),
        "Mix": (f"https://mix.com/{username}", False),
        "Yandex": (f"https://yandex.com/user/{username}", False),
        "VK": (f"https://vk.com/{username}", False),
        "OK.ru": (f"https://ok.ru/{username}", False),
        "Rutube": (f"https://rutube.ru/video/person/{username}", False),
        "Douban": (f"https://www.douban.com/people/{username}/", False),
        "Zhihu": (f"https://www.zhihu.com/people/{username}", False),
    "iFixit": (f"https://www.ifixit.com/User/{username}", False),
        "Metacritic": (f"https://www.metacritic.com/user/{username}", False),
        "Speedrun.com": (f"https://www.speedrun.com/user/{username}", False),
        "GameFAQs": (f"https://gamefaqs.gamespot.com/community/{username}", False),
        "GOG": (f"https://www.gog.com/u/{username}", False),
        "Humblr": (f"https://{username}.humblr.com", True),
        "DevRant": (f"https://devrant.com/users/{username}", False),
        "Lobsters": (f"https://lobste.rs/u/{username}", False),
        "Booth.pm": (f"https://{username}.booth.pm", True),
        "Pixiv": (f"https://www.pixiv.net/en/users/{username}", False),
        "Pluralsight": (f"https://app.pluralsight.com/profile/{username}", False),
        "Udacity": (f"https://www.udacity.com/u/{username}", False),
        "Scribd": (f"https://www.scribd.com/{username}", False),
        "Academia.edu": (f"https://{username}.academia.edu", True),
        "ResearchGate": (f"https://www.researchgate.net/profile/{username}", False),
        "OpenLibrary": (f"https://openlibrary.org/people/{username}", False),
        "Zotero": (f"https://www.zotero.org/{username}", False),
        "ORCID": (f"https://orcid.org/{username}", False),
        "Mendeley": (f"https://www.mendeley.com/profiles/{username}/", False),
        "BioStars": (f"https://www.biostars.org/u/{username}/", False),
        "PubPeer": (f"https://pubpeer.com/user/{username}", False),
        "BioRxiv": (f"https://www.biorxiv.org/user/{username}", False),
        "ArXiv": (f"https://arxiv.org/a/{username}.html", False),
        "OSF.io": (f"https://osf.io/{username}/", False),
        "Sci-Hub": (f"https://sci-hub.se/{username}", False),
        "Vox": (f"https://www.vox.com/authors/{username}", False),
        "TheVerge": (f"https://www.theverge.com/users/{username}", False),
        "BuzzFeed": (f"https://www.buzzfeed.com/{username}", False),
        "HuffPost": (f"https://www.huffpost.com/author/{username}", False),
        "NPR": (f"https://www.npr.org/people/{username}", False),
        "BBC": (f"https://www.bbc.co.uk/programmes/profiles/{username}", False),
        "CNN": (f"https://edition.cnn.com/profiles/{username}", False),
        "Reuters": (f"https://www.reuters.com/journalists/{username}", False),
        "Forbes": (f"https://www.forbes.com/sites/{username}", False),
        "Medium (custom domain)": (f"https://{username}.medium.com", True),
        "XDA Developers": (f"https://forum.xda-developers.com/m/{username}.4292613/", False),
        "StackExchange": (f"https://stackexchange.com/users/{username}", False),
        "Meta StackOverflow": (f"https://meta.stackoverflow.com/users/{username}", False),
        "ServerFault": (f"https://serverfault.com/users/{username}", False),
        "SuperUser": (f"https://superuser.com/users/{username}", False),
        "AskUbuntu": (f"https://askubuntu.com/users/{username}", False),
        "MathOverflow": (f"https://mathoverflow.net/users/{username}", False),
        "Physics StackExchange": (f"https://physics.stackexchange.com/users/{username}", False),
        "AI StackExchange": (f"https://ai.stackexchange.com/users/{username}", False),
        "Crypto StackExchange": (f"https://crypto.stackexchange.com/users/{username}", False),
        "DevOps StackExchange": (f"https://devops.stackexchange.com/users/{username}", False),
        "Software Engineering": (f"https://softwareengineering.stackexchange.com/users/{username}", False),
        "CrossValidated": (f"https://stats.stackexchange.com/users/{username}", False),
        "Bioinformatics": (f"https://bioinformatics.stackexchange.com/users/{username}", False),
        "Music StackExchange": (f"https://music.stackexchange.com/users/{username}", False),
        "Gaming StackExchange": (f"https://gaming.stackexchange.com/users/{username}", False),
        "Photography StackExchange": (f"https://photo.stackexchange.com/users/{username}", False),
        "Travel StackExchange": (f"https://travel.stackexchange.com/users/{username}", False),
        "Cooking StackExchange": (f"https://cooking.stackexchange.com/users/{username}", False),
        "Parenting StackExchange": (f"https://parenting.stackexchange.com/users/{username}", False),
        "Interpersonal StackExchange": (f"https://interpersonal.stackexchange.com/users/{username}", False),
        "Movies StackExchange": (f"https://movies.stackexchange.com/users/{username}", False),
        "English StackExchange": (f"https://english.stackexchange.com/users/{username}", False),
        "Literature StackExchange": (f"https://literature.stackexchange.com/users/{username}", False),
        "Philosophy StackExchange": (f"https://philosophy.stackexchange.com/users/{username}", False),
        "History StackExchange": (f"https://history.stackexchange.com/users/{username}", False),
        "Law StackExchange": (f"https://law.stackexchange.com/users/{username}", False),
        "Politics StackExchange": (f"https://politics.stackexchange.com/users/{username}", False),
        "Economics StackExchange": (f"https://economics.stackexchange.com/users/{username}", False),
        "The Workplace StackExchange": (f"https://workplace.stackexchange.com/users/{username}", False),
        "Writing StackExchange": (f"https://writing.stackexchange.com/users/{username}", False),
        "Skeptics StackExchange": (f"https://skeptics.stackexchange.com/users/{username}", False),
        "Science Fiction": (f"https://scifi.stackexchange.com/users/{username}", False),
        "Role-Playing Games": (f"https://rpg.stackexchange.com/users/{username}", False),
        "Board & Card Games": (f"https://boardgames.stackexchange.com/users/{username}", False),
        "Anime & Manga": (f"https://anime.stackexchange.com/users/{username}", False),
        "Code Golf": (f"https://codegolf.stackexchange.com/users/{username}", False),
        "Puzzling": (f"https://puzzling.stackexchange.com/users/{username}", False),
        "Worldbuilding": (f"https://worldbuilding.stackexchange.com/users/{username}", False),
        "Christianity": (f"https://christianity.stackexchange.com/users/{username}", False),
        "Judaism": (f"https://judaism.stackexchange.com/users/{username}", False),
        "Islam": (f"https://islam.stackexchange.com/users/{username}", False),
        "Buddhism": (f"https://buddhism.stackexchange.com/users/{username}", False),
        "Hinduism": (f"https://hinduism.stackexchange.com/users/{username}", False),
        "Meta StackExchange": (f"https://meta.stackexchange.com/users/{username}", False),
        "OpenStreetMap": (f"https://www.openstreetmap.org/user/{username}", False),
        "Mapillary": (f"https://www.mapillary.com/app/user/{username}", False),
        "Wikimedia": (f"https://meta.wikimedia.org/wiki/User:{username}", False),
        "WikiTree": (f"https://www.wikitree.com/wiki/User:{username}", False),
        "Genealogy.com": (f"https://www.genealogy.com/forum/surnames/{username}/", False),
        "FamilySearch": (f"https://www.familysearch.org/tree/person/details/{username}", False),
    "Amazon India": (f"https://www.amazon.in/shop/{username}", False),
        "Flipkart": (f"https://www.flipkart.com/user/{username}", False),
        "Zomato": (f"https://www.zomato.com/{username}", False),
        "Swiggy": (f"https://www.swiggy.com/user/{username}", False),
        "Zepto": (f"https://www.zepto.com/profile/{username}", False),
        "Blinkit": (f"https://www.blinkit.com/profile/{username}", False),
        "BigBasket": (f"https://www.bigbasket.com/user/{username}", False),
        "JioMart": (f"https://www.jiomart.com/user/{username}", False),
        "Tata Neu": (f"https://www.tatadigital.com/profile/{username}", False),
        "Paytm": (f"https://paytm.com/user/{username}", False),
        "PhonePe": (f"https://www.phonepe.com/user/{username}", False),
        "Mobikwik": (f"https://www.mobikwik.com/user/{username}", False),
        "BharatPe": (f"https://bharatpe.com/user/{username}", False),
        "Airtel Thanks": (f"https://www.airtel.in/myaccount/{username}", False),
        "Jio": (f"https://www.jio.com/selfcare/{username}", False),
        "Vi": (f"https://www.myvi.in/profile/{username}", False),
        "RedBus": (f"https://www.redbus.in/user/{username}", False),
        "IRCTC": (f"https://www.irctc.co.in/nget/profile/{username}", False),
        "MakeMyTrip": (f"https://www.makemytrip.com/profile/{username}", False),
        "Goibibo": (f"https://www.goibibo.com/user/{username}", False),
        "Yatra": (f"https://www.yatra.com/user/{username}", False),
        "OYO": (f"https://www.oyorooms.com/user/{username}", False),
        "OLA": (f"https://www.olacabs.com/profile/{username}", False),
        "Uber India": (f"https://www.uber.com/in/en/profile/{username}", False),
        "Rapido": (f"https://rapido.bike/profile/{username}", False),
        "DriveU": (f"https://www.driveu.in/profile/{username}", False),
        "Urban Company": (f"https://www.urbancompany.com/user/{username}", False),
        "Housejoy": (f"https://www.housejoy.in/profile/{username}", False),
        "Quikr": (f"https://www.quikr.com/profile/{username}", False),
        "OLX India": (f"https://www.olx.in/profiles/{username}", False),
        "JustDial": (f"https://www.justdial.com/user/{username}", False),
        "1mg": (f"https://www.1mg.com/user/{username}", False),
        "NetMeds": (f"https://www.netmeds.com/user/{username}", False),
        "PharmEasy": (f"https://www.pharmeasy.in/profile/{username}", False),
        "Tata 1mg": (f"https://www.1mg.com/user/{username}", False),
        "CureFit": (f"https://www.cure.fit/profile/{username}", False),
        "HealthifyMe": (f"https://www.healthifyme.com/user/{username}", False),
        "Naukri": (f"https://www.naukri.com/mnjuser/profile?id={username}", False),
        "Shine": (f"https://www.shine.com/u/{username}", False),
        "Monster India": (f"https://www.foundit.in/u/{username}", False),
        "FreshersWorld": (f"https://www.freshersworld.com/user/{username}", False),
        "Internshala": (f"https://internshala.com/student/profile/public/{username}", False),
        "UpGrad": (f"https://www.upgrad.com/profile/{username}", False),
        "Unacademy": (f"https://unacademy.com/@{username}", False),
        "Byju's": (f"https://byjus.com/profile/{username}", False),
        "Vedantu": (f"https://www.vedantu.com/user/{username}", False),
        "Toppr": (f"https://www.toppr.com/profile/{username}", False),
        "Doubtnut": (f"https://www.doubtnut.com/profile/{username}", False),
        "Embibe": (f"https://www.embibe.com/user/{username}", False),
        "Extramarks": (f"https://www.extramarks.com/user/{username}", False),
        "Khan Academy India": (f"https://hi-in.khanacademy.org/profile/{username}", False),
        "Jagran Josh": (f"https://www.jagranjosh.com/user/{username}", False),
        "India Today": (f"https://www.indiatoday.in/profile/{username}", False),
        "NDTV": (f"https://www.ndtv.com/user/{username}", False),
        "ABP News": (f"https://news.abplive.com/user/{username}", False),
        "Times of India": (f"https://timesofindia.indiatimes.com/user/{username}", False),
        "Hindustan Times": (f"https://www.hindustantimes.com/user/{username}", False),
        "Indian Express": (f"https://indianexpress.com/profile/author/{username}/", False),
        "Dainik Bhaskar": (f"https://www.bhaskar.com/author/{username}/", False),
        "Aaj Tak": (f"https://www.aajtak.in/profile/{username}", False)
    }
    
user_agents = [
    # Chrome on Windows
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.6422.112 Safari/537.36",
    "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.6367.78 Safari/537.36",

    # Firefox on Windows
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0",
    "Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:126.0) Gecko/20100101 Firefox/126.0",

    # Safari on macOS
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 13_5_2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1 Safari/605.1.15",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.128 Safari/537.36",

    # Edge on Windows
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.6422.112 Safari/537.36 Edg/125.0.2535.67",
    "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.6312.86 Safari/537.36 Edg/123.0.2420.65",
    
    # Chrome on Windows
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.6422.112 Safari/537.36",
    "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.6367.78 Safari/537.36",

    # Firefox on Windows
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0",
    "Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:126.0) Gecko/20100101 Firefox/126.0",

    # Safari on macOS
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 13_5_2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1 Safari/605.1.15",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.128 Safari/537.36",

    # Edge on Windows
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.6422.112 Safari/537.36 Edg/125.0.2535.67",
    "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.6312.86 Safari/537.36 Edg/123.0.2420.65",
]

known_found_status = { 
        "Facebook": [302, 403, 400], 
        "LinkedIn": [403], 
        "Steam": [302], 
        "Medium": [403], 
        "Epic Games": [403], 
        "Amazon India": [403], 
        "Flipkart": [403], 
        "Zomato": [403], 
        "Swiggy": [403], 
        "Zepto": [403], 
        "Blinkit": [403], 
        "BigBasket": [403], 
        "JioMart": [403], 
        "Tata Neu": [403], 
        "Paytm": [403], 
        "PhonePe": [403], 
        "Mobikwik": [403], 
        "BharatPe": [403], 
        "Airtel Thanks": [403], 
        "Jio": [403], 
        "Vi": [403], 
        "RedBus": [403], 
        "IRCTC": [403], 
        "MakeMyTrip": [403], 
        "Goibibo": [403], 
        "Yatra": [403], 
        "OYO": [403], 
        "OLA": [403], 
        "Uber India": [403], 
        "Rapido": [403], 
        "DriveU": [403], 
        "Urban Company": [403], 
        "Housejoy": [403], 
        "Quikr": [403], 
        "OLX India": [403], 
        "JustDial": [403], 
        "1mg": [403], 
        "NetMeds": [403], 
        "PharmEasy": [403], 
        "CureFit": [403], 
        "HealthifyMe": [403], 
        "Naukri": [403], 
        "Shine": [403], 
        "Monster India": [403], 
        "FreshersWorld": [403],
        "Internshala": [403], 
        "UpGrad": [403], 
        "Unacademy": [403], 
        "Byju's": [403], 
        "Vedantu": [403], 
        "Toppr": [403], 
        "Doubtnut": [403], 
        "Embibe": [403], 
        "Extramarks": [403], 
        "Khan Academy India": [403], 
        "Jagran Josh": [403], 
        "India Today": [403], 
        "NDTV": [403], 
        "ABP News": [403], 
        "Times of India": [403], 
        "Hindustan Times": [403], 
        "Indian Express": [403], 
        "Dainik Bhaskar": [403], 
        "Aaj Tak": [403],
         "Udemy": [403],
    "Clubhouse": [403],
    "Letterboxd": [403],
    "Last.fm": [403],
    "Goodreads": [403],
    "IMDb": [403],
    "SoundCloud": [403],
    "Mixcloud": [403],
    "Anchor": [403],
    "ReverbNation": [403],
    "Bandcamp": [403],
    "Dev.to": [403],
    "Trello": [403],
    "Canva": [403],
    "Figma": [403],
    "ProductHunt": [403],
    "AngelList": [403],
    "Crunchbase": [403],
    "IndieHackers": [403],
    "Hashnode": [403],
    "Gumroad": [403],
    "Payhip": [403],
    "Ko-fi": [403],
    "BuyMeACoffee": [403],
    "Patreon": [403],
    "TeeSpring": [403],
    "Spreadshirt": [403],
    "Zazzle": [403],
    "CafePress": [403],
    "Skillshare": [403],
    "EdX": [403],
    "FutureLearn": [403],
    "Kaggle": [403],
    "Hackerrank": [403],
    "Codeforces": [403],
    "TopCoder": [403],
    "Replit": [403],
    "TryHackMe": [403],
    "HackTheBox": [403],
    "ExploitDB": [403],
    "SecurityTrails": [403],
    "PacketStorm": [403],
    "Glitch": [403],
    "Vercel": [403],
    "Netlify": [403],
    "Surge": [403],
    "Render": [403],
    "Fly.io": [403],
    "Cloudflare Pages": [403],
    "Firebase": [403],
    "Vivaldi Forum": [403],
    "Mozilla Support": [403],
    "Opera Forums": [403],
    "Debian Forums": [403],
    "Ubuntu Forums": [403],
    "Arch Forums": [403],
    "LibreOffice": [403],
    "OpenAI Community": [403],
    "Adobe": [403],
    "Autodesk": [403],
    "Unity": [403],
    "Unreal Engine": [403],
    "GDevelop": [403],
    "Godot": [403],
    "Itch.io": [403],
    "GameJolt": [403],
    "ModDB": [403],
    "IndieDB": [403],
    "Gamebanana": [403],
    "FanFiction": [403],
    "AO3": [403],
    "Wattpad": [403],
    "Quotev": [403],
    "RoyalRoad": [403],
    "Tapas": [403],
    "Webtoons": [403],
    "MyAnimeList": [403],
    "AniList": [403],
    "Kitsu": [403],
    "Trakt": [403],
    "TV Time": [403],
    "Discogs": [403],
    "Bandlab": [403],
    "Mix": [403],
    "Yandex": [403],
    "VK": [403],
    "OK.ru": [403],
    "Rutube": [403],
    "Douban": [403],
    "Zhihu": [403],
    "iFixit": [403],
    "Metacritic": [403],
    "Speedrun.com": [403],
    "GameFAQs": [403],
    "GOG": [403],
    "Humblr": [403],
    "DevRant": [403],
    "Lobsters": [403],
    "Instagram": [403],
    "Twitter": [403],  # sometimes used for suspended or protected accounts
    "LinkedIn": [403],
    "Steam": [302],
    "Medium": [403],
    "Epic Games": [403],
    "WordPress": [403],  # exists but blocks bots
    "Substack": [403],
    "Tumblr": [403],
    "Telegram": [200],
    "Reddit": [403],  # ambiguous: use with caution
    "Snapchat": [403],
    "Pinterest": [403],
    "Flickr": [403],
    "Twitch": [403],
    "Discord": [403],
    "Bitbucket": [403],
    "Patreon": [403],
    "Bandcamp": [403],
    "Replit": [403],
    "GitLab": [403],
    "GitHub": [403],
    "Notion": [403],
    "Ghost": [403],
    "Blogger": [403],
    "Fitbit": [403],
    "Strava": [403],
    "Booth.pm": [403],
    "Pixiv": [403],
    "Pluralsight": [403],
    "Udacity": [403],
    "Scribd": [403],
    "Academia.edu": [403],
    "ResearchGate": [403],
    "OpenLibrary": [403],
    "Zotero": [403],
    "ORCID": [403],
    "Mendeley": [403],
    "BioStars": [403],
    "PubPeer": [403],
    "BioRxiv": [403],
    "ArXiv": [403],
    "OSF.io": [403],
    "Sci-Hub": [403],
    "Vox": [403],
    "TheVerge": [403],
    "BuzzFeed": [403],
    "HuffPost": [403],
    "NPR": [403],
    "BBC": [403],
    "CNN": [403],
    "Reuters": [403],
    "Forbes": [403],
    "Medium (custom domain)": [403],
    "XDA Developers": [403],
    "StackExchange": [403],
    "Meta StackOverflow": [403],
    "ServerFault": [403],
    "SuperUser": [403],
    "AskUbuntu": [403],
    "MathOverflow": [403],
    "Physics StackExchange": [403],
    "AI StackExchange": [403],
    "Crypto StackExchange": [403],
    "DevOps StackExchange": [403],
    "Software Engineering": [403],
    "CrossValidated": [403],
    "Bioinformatics": [403],
    "Music StackExchange": [403],
    "Gaming StackExchange": [403],
    "Photography StackExchange": [403],
    "Travel StackExchange": [403],
    "Cooking StackExchange": [403],
    "Parenting StackExchange": [403],
    "Interpersonal StackExchange": [403],
    "Movies StackExchange": [403],
    "English StackExchange": [403],
    "Literature StackExchange": [403],
    "Philosophy StackExchange": [403],
    "History StackExchange": [403],
    "Law StackExchange": [403],
    "Politics StackExchange": [403],
    "Economics StackExchange": [403],
    "The Workplace StackExchange": [403],
    "Writing StackExchange": [403],
    "Skeptics StackExchange": [403],
    "Science Fiction": [403],
    "Role-Playing Games": [403],
    "Board & Card Games": [403],
    "Anime & Manga": [403],
    "Code Golf": [403],
    "Puzzling": [403],
    "Worldbuilding": [403],
    "Christianity": [403],
    "Judaism": [403],
    "Islam": [403],
    "Buddhism": [403],
    "Hinduism": [403],
    "Meta StackExchange": [403],
    "OpenStreetMap": [403],
    "Mapillary": [403],
    "Wikimedia": [403],
    "WikiTree": [403],
    "Genealogy.com": [403],
    "FamilySearch": [403],
    "Amazon India": [403],
    "Flipkart": [403],
    "Zomato": [403],
    "Swiggy": [403],
    "Zepto": [403],
    "Blinkit": [403],
    "BigBasket": [403],
    "JioMart": [403],
    "Tata Neu": [403],
    "Paytm": [403],
    "PhonePe": [403],
    "Mobikwik": [403],
    "BharatPe": [403],
    "Airtel Thanks": [403],
    "Jio": [403],
    "Vi": [403],
    "RedBus": [403],
    "IRCTC": [403],
    "MakeMyTrip": [403],
    "Goibibo": [403],
    "Yatra": [403],
    "OYO": [403],
    "OLA": [403],
    "Uber India": [403],
    "Rapido": [403],
    "DriveU": [403],
    "Urban Company": [403],
    "Housejoy": [403],
    "Quikr": [403],
    "OLX India": [403],
    "JustDial": [403],
    "1mg": [403],
    "NetMeds": [403],
    "PharmEasy": [403],
    "Tata 1mg": [403],
    "CureFit": [403],
    "HealthifyMe": [403],
    "Naukri": [403],
    "Shine": [403],
    "Monster India": [403],
    "FreshersWorld": [403],
    "Internshala": [403],
    "UpGrad": [403],
    "Unacademy": [403],
    "Byju's": [403],
    "Vedantu": [403],
    "Toppr": [403],
    "Doubtnut": [403],
    "Embibe": [403],
    "Extramarks": [403],
    "Khan Academy India": [403],
    "Jagran Josh": [403],
    "India Today": [403],
    "NDTV": [403],
    "ABP News": [403],
    "Times of India": [403],
    "Hindustan Times": [403],
    "Indian Express": [403],
    "Dainik Bhaskar": [403],
    "Aaj Tak": [403]
}
categorized_platforms = {
    "social_media": [
        "Facebook", "Instagram", "Twitter", "LinkedIn", "YouTube", "TikTok", "Snapchat", "Pinterest",
        "Reddit", "Tumblr", "Medium", "WordPress", "Substack", "Mastodon", "Bluesky", "Koo", "MeWe",
        "Parler", "Lemmy", 'Clubhouse'
    ],
    "messaging": [
        "Telegram", "Discord", "Signal", "WhatsApp", "Messenger"
    ],
    "developer": [
        "GitHub", "GitLab", "Bitbucket", "StackOverflow", "CodePen", "JSFiddle"
    ],
    "creative_design": [
        "Dribbble", "Behance", "Flickr", "DeviantArt", "ArtStation", "500px", 'Pixiv'
    ],
    "video_streaming": [
        "Twitch", "Vimeo", "Dailymotion", "Bilibili", "Trakt", "TV Time"
    ],
    "gaming": [
        "Steam", "Roblox", "Epic Games", "Xbox", "PlayStation", "Chess.com", "Lichess", "Speedrun.com",
        "GameFAQs", "GOG", "Itch.io", "GameJolt", "ModDB", "IndieDB", "Gamebanana"
    ],
    "adult": [
        "Pornhub", "Redtube", "XVideos", "XHamster"
    ],
    "ecommerce_marketplace": [
        "eBay", "Etsy", "Depop", "AliExpress", "Amazon", "Amazon India", "Flipkart", "Zepto", "Swiggy",
        "Blinkit", "BigBasket", "JioMart", "Tata Neu", "Zomato"
    ],
    "finance_crypto": [
        "CoinMarketCap", "Coinbase", "Binance", "Robinhood", "TradingView", "Paytm", "PhonePe",
        "Mobikwik", "BharatPe"
    ],
    "forums": [
        "Quora", "4chan", "HackerNews", "Lemmy", "XDA Developers", "StackExchange", "Meta StackOverflow","Wikimedia",
        "Lobsters",
        "ServerFault", "SuperUser", "AskUbuntu", "MathOverflow", "Physics StackExchange", "AI StackExchange",
        "Crypto StackExchange", "DevOps StackExchange", "Software Engineering", "CrossValidated",
        "Bioinformatics", "Music StackExchange", "Gaming StackExchange", "Photography StackExchange",
        "Travel StackExchange", "Cooking StackExchange", "Parenting StackExchange", "Interpersonal StackExchange",
        "Movies StackExchange", "English StackExchange", "Literature StackExchange", "Philosophy StackExchange",
        "History StackExchange", "Law StackExchange", "Politics StackExchange", "Economics StackExchange",
        "The Workplace StackExchange", "Writing StackExchange", "Skeptics StackExchange", "Science Fiction",
        "Role-Playing Games", "Board & Card Games", "Anime & Manga", "Code Golf", "Puzzling", "Worldbuilding",
        "Christianity", "Judaism", "Islam", "Buddhism", "Hinduism", "Meta StackExchange"
    ],
    "blogging_cms": [
        "Ghost", "Blogger", "Notion", "Medium (custom domain)"
    ],
    "fitness_lifestyle": [
        "Strava", "Fitbit", "CureFit", "HealthifyMe"
    ],
    "education_learning": [
        "Khan Academy", "Coursera", "Udemy", "Skillshare", "EdX", "FutureLearn", "Pluralsight", "Udacity", "Goodreads",
        "Scribd", "Academia.edu", "ResearchGate", "OpenLibrary", "Zotero", "ORCID", "Mendeley", "BioStars",
        "PubPeer", "BioRxiv", "ArXiv", "OSF.io", "Sci-Hub", "UpGrad", "Unacademy", "Byju's", "Vedantu",
        "Toppr", "Doubtnut", "Embibe", "Extramarks", "Khan Academy India", "Jagran Josh"
    ],
    "audio_music": [
        "SoundCloud", "Mixcloud", "Anchor", "ReverbNation", "Bandcamp", "Bandlab", "Discogs"
    ],
    "developers' tools": [
        "Dev.to", "Trello", "Canva", "Figma", "ProductHunt", "AngelList", "Crunchbase", "IndieHackers",
        "Hashnode", "Gumroad", "Payhip", "Ko-fi", "BuyMeACoffee", "Patreon", "TeeSpring", "Spreadshirt",
        "Zazzle", "CafePress", "Kaggle", "Hackerrank", "Codeforces", "TopCoder", "Replit", "TryHackMe",
        "HackTheBox", "ExploitDB", "SecurityTrails", "PacketStorm", "Glitch", "Vercel", "Netlify",
        "Surge", "Render", "Fly.io", "Cloudflare Pages", "Firebase",'DevRant'
    ],
    "tech_support": [
        "Vivaldi Forum", "Mozilla Support", "Opera Forums", "Debian Forums", "Ubuntu Forums", "Arch Forums",
        "LibreOffice", "OpenAI Community", "Adobe", "Autodesk"
    ],
    "game_engines": [
        "Unity", "Unreal Engine", "GDevelop", "Godot"
    ],
    "writing_fiction": [
        "FanFiction", "AO3", "Wattpad", "Quotev", "RoyalRoad", "Tapas", "Webtoons"
    ],
    "anime": [
        "MyAnimeList", "AniList", "Kitsu","Booth.pm", 
    ],
    "miscellaneous": [
        "IMDb", "Mix", "Yandex", "VK", "OK.ru", "Rutube", "Douban", "Zhihu", "iFixit", "Metacritic",
        "Humblr"
    ],
    "news_media": [
        "Vox", "TheVerge", "BuzzFeed", "HuffPost", "NPR", "BBC", "CNN", "Reuters", "Forbes",
        "India Today", "NDTV", "ABP News", "Times of India", "Hindustan Times", "Indian Express",
        "Dainik Bhaskar", "Aaj Tak"
    ],
    "transport_travel": [
        "RedBus", "IRCTC", "MakeMyTrip", "Goibibo", "Yatra", "OYO", "OLA", "Uber India", "Rapido",
        "DriveU", "Urban Company", "Housejoy"
    ],
    "classifieds": [
        "Quikr", "OLX India", "JustDial"
    ],
    "health_pharma": [
        "1mg", "NetMeds", "PharmEasy", "Tata 1mg"
    ],
    "jobs": [
        "Naukri", "Shine", "Monster India", "FreshersWorld", "Internshala"
    ],
    "telecom": [
        "Airtel Thanks", "Jio", "Vi"
    ],
    "others":[
        "FamilySearch", "Last.fm", 'Letterboxd', 'OpenStreetMap', 'Mapillary','WikiTree', 'Genealogy.com'
    ]
}
known_patterns = {
    "Instagram": ["sorry, this page isn't available", "page isn't available"],
    "Twitter": ["this account doesn’t exist", "account suspended", "page doesn’t exist"],
    "Facebook": ["this content isn't available", "profile not available"],
    "Reddit": ["page not found", "nobody on reddit goes by that name"],
    "GitHub": ["there isn’t a github pages site here", "not found", "the page could not be found"],
    "LinkedIn": ["profile not found", "this profile is not available"],
    "Pinterest": ["sorry, we couldn’t find that page"],
    "Medium": ["404 - not found", "this page doesn’t exist"],
    "Tumblr": ["there’s nothing here", "we couldn’t find the page you’re looking for"],
    "Flickr": ["we couldn’t find anything"],
    "SoundCloud": ["we can’t find that user", "we can’t find the page you requested"],
    "Twitch": ["this channel is offline", "the page you were looking for does not exist"],
    "YouTube": ["this channel does not exist", "this page isn't available", "channel not found"],
    "Steam": ["the specified profile could not be found"],
    "TikTok": ["couldn’t find this account", "this account doesn’t exist"],
    "Telegram": ["this user doesn’t exist"],
    "DeviantArt": ["the page you’re looking for couldn’t be found"],
    "Vimeo": ["we couldn’t find that page"],
    "Roblox": ["user not found", "looks like this page doesn’t exist"]
}
proxies = [
    "http://165.225.112.163:10605",
    "http://103.105.49.53:80",
    "http://103.160.201.76:8080",
    "http://51.158.68.68:8811",
    "http://8.219.97.248:80",
    "http://103.49.202.252:80",
    "http://35.154.216.140:3128",
    "http://91.203.114.74:1234",
    "http://103.167.34.10:80",
    "http://182.253.109.41:8080",
    "http://163.172.59.200:8080",
    "http://107.167.24.130:80",
    "http://103.162.12.212:8080",
    "http://110.34.3.229:3128",
    "http://200.105.215.22:33630",
]
